@startuml
class Title {
    - tconst : String
    - primaryTitle : String
    - originalTitle : String
    - isAdult : boolean
    - startYear : LocalDate
    - endYear : LocalDate
    - runtimeMinutes : Long
}

enum TitleType {
    MOVIE
    SHORT
    TVSERIES
    TVEPISODE
    VIDEO
}

enum Genre {
    Action
    Comedy
    Documentary
    Romance
    Sci-Fi
    . . . .
    . . . .
}

class AlsoKnownAs {
    - titleId : String
    - ordering : Integer
    - title : String
    - region : String
    - language : String
    - String attributes : String
    - isOriginalTitle : boolean
}

enum Types {
    alternative
    dvd
    festival
    imdbDisplay
    . . . . .
    . . . . .
}

class Crew {
    - tconst : String
}

class Person {
    - nconst : String
    - String primaryName : String
    - birthYear : LocalDate
    - deathYear : LocalDate
    - primaryProfession : List<Profession>
}

enum Profession {
    actor
    actress
    director
    music_department
    make_up_department
    producer
    soundtrack
    writer
    . . . .
    . . . .
}
class Principals{
   - tconst : String
   - nconst : String
   - category : String
   - job : String
   - characters : String
}
class Ratings{
    - tconst : String
    - averageRating : Double
    - numVotes : Integer

}
class Episode{
    - tconst : String
    - parentTconst : List<String>
    - seasonNumber : Integer
    - episodeNumber : Long
}
Title --> TitleType
Title "1"-->"*" Genre
Title "1"-->"*" AlsoKnownAs
Episode "*" --o "1" Title
Ratings "*" --o "1" Title
Person "1"-->"*" Profession
AlsoKnownAs "1"-->"*" Types
Crew "1"-->"*" Person: writer >
Crew "1"-->"*" Person: Director >
Title ""--"" Person
(Title, Person) ... Principals
@enduml