@startuml

skinparam minClassWidth 50

class Movie {
    - id : Long
    - budget : Long
    - genres : List<Genre>
    - homepage : String
    - keywords : List<Keyword>
    - String originalLanguage : String
    - String originalTitle : String
    - String overView : String
    - Double popularity : Double
    - productionCompanies : List<ProductionCompany>
    - productionCountries : List<ProductionCountry>
    - releaseDate : LocalDate
    - revenue : Long
    - runtime : Integer
    - spokenLanguages : List<SpokenLanguage>
    - status : Status
    - tagline : String
    - title : String
    - voteAverage : Double
    - voteCount : Integer
}

class Genre {
    id : Long
    name : String
}

class Keyword {
    id : Long
    name : String;
}

enum Gender {
    Male(1)
    Female(2)
}

class ProductionCompany {
    - id : Long
    - name : String
}

class ProductionCountry {
    - iso : String
    - name : String
}

class SpokenLanguage {
    - iso : String
    - name : String
}

enum Status {
    Released
}

class Credit {
    - movieId : Long
    - title : String
    - castList : List<Cast>
    - crewList : List<Crew>
}

class Cast {
    - castId : Long
    - character : String
    - creditId : String
    - gender : Gender
    - id : Long
    - name : String
    - order : Integer
}

class Crew {
    - creditId : Long;
    - department : Department;
    - gender : Gender;
    - id : Long;
    - job : Job;
    - name : String;
}

enum Job {

}

enum Department {
    Editing
    Camera
    Sound
    Writing
    Production
    Art
    Directing
    CostumeAndMakeUp
    Crew
}

Movie -> "1..*" Genre
Movie -> "1..*" Keyword
Movie -> "1..*" ProductionCompany
Movie -> "1..*" ProductionCountry
Movie -> "1..*" SpokenLanguage
Movie *-- Credit
Movie --> "1" Status
Credit -- "*" Crew
Credit -- "*" Cast
Crew --> "1..*" Department
Crew --> "1..*" Job
Crew --> "1" Gender
Cast --> "1" Gender

@enduml