name: Run Gradle Build
on: [push, pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt-hotspot'
        java-version: '11.0.10'
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1.0.4
    - name: Build with Gradle
      run: ./gradlew clean build
